### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ardalann** [atahani/reactjs-unsplash#1]
1. Use `babel-preset-env`.
1. If you don't want to worry about the Webpack or Babel setup, use `create-react-app`. It creates an almost perfect setup for most React projects.
1. No need to use the `jsx` extension. It doesn't really add any value.
1. In my experience, using redux-saga makes things unnecessarily complicated and makes it harder to onboard new developers. We avoid using it.
1. I strongly recommend [the container-component approach](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) over your current approach. By keeping all the `withRouter` usages and component Redux integrations in the containers, you can test components much more easily. 
1. I recommend static typing using Flow with React. Flow types can also replace `PropTypes` and Redux `constants`. You can also use `eslint-plugin-flowtype` to enforce Flow types for every JS file.
1. In my experience, developers care more about writing and maintaining tests when the test files are always in front of them! That's why I avoid creating a separate directory for tests. For example, if I'm writing tests for a function defined in `index.js`, I create a test file in the same directory called `index.spec.js`.
1. Look into using Travis for your open-source projects on Github. It makes automated testing and PR reviews much easier.

Really good job overall 👍  Khaste nabashi Ahmad jan.

**Comment by atahani** [comment]
Thanks ever so much for your suggestions. We talked with each other privately. I know it's too late to comment and close this issue.
